title: Health Companion Super App
description: UX/UI design of a mobile app that allow users to set reminders, track their medication usage and communicate with healthcare professionals.
show_downloads: true
google_analytics:
theme: jekyll-theme-architect